name: example
recipe: wordpress
config:
  webroot: public
  id: projectid
  via: nginx
  database: mariadb
  xdebug: false


proxy:
  appserver_nginx:     # Optional: if you exclude this, Lando will serve it as example.lndo.site
    - example.test


